development:
  adapter: postgresql
  encoding: unicode
  database: darpdu335bbqq9
  username: ufqxxvtfqfqefd
  password: 24e404af0909691d9c62091487731412a5801f19e3ced25d98d6b8b3b8a47529
  host: ec2-34-255-225-151.eu-west-1.compute.amazonaws.com
  port: 5432
  pool: 5


production:
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false


production:
  adapter: postgresql
  statement_limit: 200